# Generated by Django 4.2 on 2023-04-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
